feat: add fix-yaml action
alphaprime-dev/fix-yaml-in-another-repo pull request #1
Opened 2022-04-01 08:26 UTC by JunHCha

2022-04-01 08:58 UTC, JunHCha commented
@sawaca96 @sjquant 리뷰부탁드립니다!

2022-04-04 00:28 UTC, sawaca96 requested changes
.DS_Store는 gitignore에 있는데 commit된것 같아요.

2022-04-04 00:28 UTC, sawaca96 commented on .python-version
> +bump-k8s
이 파일은 gitignore에 들어가야 할 것 같습니다.

2022-04-04 00:28 UTC, sawaca96 commented on fix-yaml/__main__.py
> +        print("raise")
이곳에 print가 필요한건가요?

2022-04-04 00:35 UTC, JunHCha commented on fix-yaml/__main__.py
> +        print("raise")
수정했습니다! [e19deeb](https://github.com/alphaprime-dev/fix-yaml-in-another-repo/pull/1/commits/e19deeb45848bebc21bfcfddef76cec12e5a5420)

2022-04-04 00:35 UTC, JunHCha commented on .python-version
> +bump-k8s
수정했습니다! [8f60ae2](https://github.com/alphaprime-dev/fix-yaml-in-another-repo/pull/1/commits/8f60ae219689cf71f581fd1a2a378085f73f7f7b)

2022-04-04 00:52 UTC, sawaca96 approved these changes
고생하셨습니다. 👍 `.DS_Store` 체크 후 병합해주세요

2022-04-04 06:40 UTC, sjquant commented on fix-yaml/__main__.py
> +)
```suggestion
subprocess.run(["git", "config", "user.name", "github-actions"], check=True)
subprocess.run(
    ["git", "config", "user.email", "github-actions@github.com"],
    check=True,
)
```

이 부분 역시 기본값을 포함하여 변수로 받아주면 좋을 것 같습니다.

2022-04-04 06:40 UTC, sjquant commented
혹시 테스트를 어떻게 해보면 될까요? @JunHCha

2022-04-04 06:43 UTC, JunHCha commented
[alphaprime-dev/fix-yaml-in-another-repo-test](https://github.com/alphaprime-dev/fix-yaml-in-another-repo-test/blob/main/.github/workflows/fix-yaml.yaml)에서 main branch의 workflow에서 inputs 값을 수정하고 push하면 target-branch의 values.yaml이 수정되는 것을 확인할 수 있습니다.

2022-04-04 06:45 UTC, sjquant commented
@JunHCha 추가적으로, `key_val_pairs`가 조금 verbose한 느낌이 드는데, 그냥 `values`로 적어주는건 어떻게 생각하시나요 (P5)

2022-04-04 06:47 UTC, JunHCha commented
> @JunHCha 추가적으로, `key_val_pairs`가 조금 verbose한 느낌이 드는데, 그냥 `values`로 적어주는건 어떻게 생각하시나요 (P5)

그렇게 수정하겠습니다!

2022-04-04 06:53 UTC, sjquant commented
@JunHCha 
![image](https://user-images.githubusercontent.com/16596777/161489034-471993c0-020e-4226-b5ac-b44b36b3f44f.png)

test repo에 다음과 같은 케이스가 실패했는데 확인부탁드립니다.

2022-04-04 07:10 UTC, JunHCha commented
@sjquant val에 list 형태도 받을 수 있도록 수정했습니다!

2022-04-04 07:19 UTC, sjquant commented on requirements.txt
> +pyyaml
버전은 명시해주는게 좋을거 같습니다. 해당 라이브러리들에 나중에 Breaking Changes가 발생하면 저희도 깨지게 됩니다.

2022-04-04 07:30 UTC, JunHCha commented on requirements.txt
> +pyyaml
[2417d5a](https://github.com/alphaprime-dev/fix-yaml-in-another-repo/pull/1/commits/2417d5addc78eea77063aff9ad3d384082e3ecce) 수정했습니다!

2022-04-04 07:30 UTC, sjquant approved these changes
Good

2022-04-04 07:30 UTC, sjquant commented
고생했습니다!

2022-04-04 07:49 UTC, merged